apiVersion: server.eidolonai.com/v1alpha1
kind: Machine
metadata:
  # Name of the machine. This must be unique within the namespace and be a valid DNS subdomain.
  name: eidolon-sample

spec:
  image: my-eidolon-project:latest # The image to use for the machine. Set this for production or cloud based environments
  imagePullPolicy: Never # WARNING: Change this for production or cloud based environments
  # The environment variables to set in the machine. In this case, we are using a secret to set the environment variables named `eidolon`.
  # These secrets are set up by the makefile
  envFrom:
    - secretRef:
        name: eidolon
  # The symbolic memory implementation to use for the machine. In this case, we are using the `LocalSymbolicMemory` implementation.
  # WARNING: This is ephemeral memory and will be lost when the machine is deleted or restarted.
  symbolic_memory: LocalSymbolicMemory
