name: Start Server
description: Start agent server and check it is running

runs:
  using: 'composite'
  steps:
    - name: start server
      shell: bash
      run: |
        set +o pipefail
        yes TESTVALUE | make docker-serve ARGS="--detach"
        set -o pipefail
    - name: check server is running
      shell: bash
      run: |
        start_time=$(date +%s)
        timeout=60
        
        while true; do
          current_time=$(date +%s)
          elapsed=$((current_time - start_time))
          
          response=$(curl -sS -X GET 'http://localhost:8080/system/health' -H 'accept: application/json' -o /dev/null -w "%{http_code}" --connect-timeout 2 --max-time 2 || echo "connection reset")
          if [ "$response" = "200" ]; then
            echo "Server is up and running"
            exit 0
          fi
        
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout reached. Server did not respond within 5 minutes."
            exit 1
          fi
          sleep 1
        done
    - name: Capture Docker Compose logs
      if: failure()
      shell: bash
      run: docker compose logs > docker-compose-logs.txt
    - name: Upload Docker Compose logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: docker-compose-logs
        path: docker-compose-logs.txt
