name: Synchronize
on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: "Updating Dependencies"
        run: |
          git config --global user.email "autosync@eidolonai.com"
          git config --global user.name "autosync"
          if [ "${{ github.repository }}" == "eidolon-ai/agent-machine" ]; then
            make update
          else
            make sync
          fi
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bumping eidolon version"
